config/routes.rb
Rails.application.routes.draw do


  root 'home#index'
  resources :posts, except: [:index]
  resources :authors, only: [:show]
  
  get '/signup' => 'authors#new'
  post '/signup' => 'authors#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  post '/like' => 'likes#create'
  get '/hashtag' => 'home#index'

  get '/stats' => 'stats#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @author = session[:author_id]
    if params[:hashtag]
        @posts = Post.where(hashtag: params[:hashtag])
    else
        @posts = Post.all
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_meta.html.erb
<section class="meta">
    <ul>
        <% if logged_in?(@author) %>
        <li>
            <%= link_to '<i class="fa fa-home"></i>'.html_safe, root_path %>
        </li>
        <li>
            <%= link_to '<i class="fa fa-user"></i>'.html_safe, author_path(@author) %>
        </li>
        <li>
            <%= link_to '<i class="fa fa-bar-chart"></i>'.html_safe, stats_path %>
        </li>
        <li>
            <a href=""><%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_post_path %></a>
        </li>
        <li>
            <%= link_to '<i class="fa fa-sign-out"></i>'.html_safe, logout_path, method: :delete %>
        </li>
        <% else %>
            <li>
                <%= link_to '<i class="fa fa-home"></i>'.html_safe, root_path %>
            </li>
            <li>
                <%= link_to '<i class="fa fa-user"></i>'.html_safe, login_path %>
            </li>
            <li>
                <%= link_to '<i class="fa fa-bar-chart"></i>'.html_safe, stats_path %>
            </li>
        <% end %>
    </ul>
</section>

app/views/home/index.html.erb
<div class="container">
    <header class="site-head">
        <div>
            <span><img src="http://fivethotpresents.com/wp-content/uploads/2014/07/GA_logo_FF0033.png" alt=""></span>
            <h1>
                <a href="#">Today I Learned <%= @hashtag %></a>
                <!-- <span><img src="http://fivethotpresents.com/wp-content/uploads/2014/07/GA_logo_FF0033.png" alt=""></span> -->
            </h1>
        </div>
        <%= render 'meta' %>
    </header>

    <section id="home">
        <article class="post">
        <% @posts.reverse.each do |post| %>
            <section>
                <div class="post-content">
                    <h1>
                        <a href="#"><%= post.title %></a>
                    </h1>
                    <%= post.body.html_safe %>
                    <footer>
                    <p>
                    <a href="/author/jakeworth"><%= post.author.username %></a>
                    <br>
                    <a class="post__permalink" href="#"><%= post.created_at.strftime("%B %d, %Y") %></a>
                    </p>
                    </footer>
                </div>
                <aside>
                <ul>
                <li>
                    <a class="hashtag" href="/?hashtag=<%= post.hashtag %>">#<%= post.hashtag %></a>
                </li>
                <li>
                    <a class="save" target="_blank" href="#">share
                    </a>
                </li>
                <li>
                    <a class="js-like-action post__like-link" data-id="<%= post.id %>" href="#"><i class="fa fa-heart-o"></i>
                    <span class="like-label"><%= post.liking_authors.count %></span>
                    </a>
                </li>
                </ul>
                </aside>
            </section>
        <% end %>
        </article>
    </section>
</div>